### ISSUE TITLE
Ubah summary.md ke readme.md

### ISSUE THREAD

**Issue by syukronarie** [zhafranafif/react_Zhafran-Afif#4]
Semua file summary.md harus direname menjadi readme.md, jadi tidak ada lagi file summary.md

**Comment by zhafranafif** [comment]
Done mas arie

**Comment by syukronarie** [comment]
mana nomor PR yg fixed issue ini?

**Comment by zhafranafif** [comment]
maksudnya gimana mass?

**Comment by zhafranafif** [comment]
https://github.com/zhafranafif/react_Zhafran-Afif/commit/573a38d30eecdc39f419176de74b943d355f9c45 seperti ini mas?

**Comment by syukronarie** [comment]
> [573a38d](https://github.com/zhafranafif/react_Zhafran-Afif/commit/573a38d30eecdc39f419176de74b943d355f9c45) seperti ini mas?

OK
